Riya parquet
prod-lab/RiskNet pull request #11
Opened 2024-01-24 05:49 UTC by riyamhatre

Description of changes
- the code to load the data had to be modified to read the parquet files 
- parquet.py has a function called parquet_convert that converts the txt files to parquet and stores them in whatever folder you specify --> need to modify it to be more generic/dsmlp-friendly 
- the "notebooks" folder has some EDA that will be useful for later
Things to add later 
- generic file path

2024-01-24 06:04 UTC, emchin requested changes
These parquet additions look super cool!! Very excited (especially since it allows more data to be accessed/we no longer have to limit to nrows=1M?! 👀 )

Only two reviewing comments: a note on pyarrow, and a note on filepaths.

Thank you for PR'ing! ❤️ Feel free to message me in slack if you have questions about my comments.

2024-01-24 06:04 UTC, emchin commented on src/risknet/run/pipeline.py
> +monthly_path = '/Users/riyamhatre/Downloads/historical_data_2009Q1/historical_data_time_2009Q1.txt'
This line looks like it can be replaced with the personalized path that was added in the recent PR

See the current version of `pipeline.py` line 23-24:
`risknet_run_path = os.path.join(os.path.dirname(os.path.dirname(__file__)),'run')
sys.path.append(risknet_run_path)`

Possibly modify to something like this?

2024-01-24 06:04 UTC, emchin commented on src/risknet/run/pipeline.py
> +monthly_path = '/Users/riyamhatre/Downloads/historical_data_2009Q1/historical_data_time_2009Q1.txt'
This applies to all mentions of fm_root or paths (there are multiple mentions in this `pipeline.py` file

2024-01-24 06:04 UTC, emchin commented on src/risknet/proc/label_prep.py
> +import pyarrow as pa
If we're using pyarrow now, can you specify a pyarrow import version number in `setup.cfg` so everyone is using the same version/it works consistently?

You can find your version of pyarrow by going to your VSCode, entering Python on the terminal, and printing the version number there.

2024-01-24 06:20 UTC, riyamhatre commented on src/risknet/proc/label_prep.py
> +import pyarrow as pa
ah I forgot to remove this import (I was trying something out before but turns out I don't need pyarrow lol)

2024-01-24 06:21 UTC, riyamhatre commented on src/risknet/run/pipeline.py
> +monthly_path = '/Users/riyamhatre/Downloads/historical_data_2009Q1/historical_data_time_2009Q1.txt'
hm okay yea I'll see what I can do with the file path

2024-01-27 01:09 UTC, emchin requested changes
One more requested change: please make sure the VSCode out-of-memory `killed` code error is fixed BEFORE merging with main 👍

2024-01-31 07:17 UTC, Zhfang01 commented
I'm on board with Emily's thoughts. Other than that, it all looks good!

2024-02-02 21:53 UTC, closed without merging